print "got inside init"
from main import *
from home import *
from signin import *
from signup import *
from update_profile import *
from createSharedCalendar import *
from oauth2callback import *
from signout import *
